//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string Summary { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
